## Exception Handling 

In [1]:
### Task 1

In [8]:
# 1. 
def divisonByZero() :
    while True :
        try :
            num1 = int(input("Enter a value1 : "))
            num2 = int(input("Enter a value2 : "))
            value = num1/num2
        except ZeroDivisionError: 
            print(ZeroDivisionError)
        else :
            print(value)
            break

In [9]:
divisonByZero()

Enter a value1 : 5
Enter a value2 : 0
<class 'ZeroDivisionError'>
Enter a value1 : 23
Enter a value2 : 23
1.0


In [31]:
# 2. Generate Sentences
subjects=["Americans","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]
def generateSentences(subjects,verbs, objects) :
    for sub in subjects :
        for ver in verbs :
            for obj in objects :
                print(sub+" " + ver + " " + obj)

In [33]:
generateSentences(subjects,verbs,objects)

Americans play Baseball
Americans play Cricket
Americans watch Baseball
Americans watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


In [34]:
## Task 2

In [35]:
lst = ['list',"vikas", "pal"]
lst

['list', 'vikas', 'pal']

In [37]:
type(iter(lst))

list_iterator

In [45]:
f = open('test.txt', 'w')
f.write("write the content of the file")

29

In [48]:
f = open('test.txt', 'r', encoding='utf-8')
f.read(5)

'write'

## Vander Matrix : 


In [67]:
import numpy as np

In [88]:
import math
items = [1,2,3]
N = 4;
M = len(items)
result = np.zeros([M,N])

for i in range(M) :
    k = 0
    for j in range(N-1,-1,-1) :
        result[i][j] = int(math.pow(items[i],k))
        k +=1
        

In [94]:
print(result)

[[ 1.  1.  1.  1.]
 [ 8.  4.  2.  1.]
 [27.  9.  3.  1.]]


In [95]:
result.astype(int)

array([[ 1,  1,  1,  1],
       [ 8,  4,  2,  1],
       [27,  9,  3,  1]])

In [96]:
np.vander(items, N)

array([[ 1,  1,  1,  1],
       [ 8,  4,  2,  1],
       [27,  9,  3,  1]])